### ISSUE TITLE
Do not use same black card more than once

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#119]
A game should not use the same black card more than once.

Solution 1:
Track which black cards has been used for a game. Either this could be tracked via having a BlackCardRef table, similar to that we have for white card. Such a table could consist of blackCard id and game key and card state. The game would have a one to one relation with the BlackCardRef. Each time when looking for a new black card, we could filter out black cards that exist in BlackCardRef for that game. Similar to what we do in getUniqueWhiteCard query.

Solution 2:
Black card lives on the turn table instead of the game table. When starting a game, all black cards are generated and stored on each turn. To retrieve a black card from a game, one would do game.currentTurn.blackCard or something like that.

Benefit of solution 1
Uses the same method as for white card. This will probably make the system to make more sense, doing it the same way for white cards and black cards. Treating them the same way. It does also give us the possibility to store more game specific info on a black card in the future.

Benefit of solution 2
Probably more efficient to only query for the black card once, and store them on GameTurn table. Probably a bit faster and easier to implement as well.

### Requirements:
- [x] Black card can only occur once per game

### Tasks
- [x] Create `BlackCardRef` model with relation to `BlackCard`
- [x] Create relation between `Game` and `BlackCardRef`
- [x] Remove relation between `Game` and `BlackCard`
- [x] Alter `Game.newBlack` function to create a BlackCardRef and relate to it.
- [x] `getUnusedBlack` filter cards on cardRef table, similar to whitecard query
