### ISSUE TITLE
Start game Epic

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#19]
### Intro
Make it possible to start game from lobby screen. When the game is started, each user should be given the correct amount of cards specified in `game.play_cards`.

### User story
As a user i want to be able to start my game from the lobby screen. When i start my game i want to be given my initial playing cards. The amount of cards i receive should be the same as specified in the game settings.

I should be able to see my card somewhere on the screen, so that i can easily understand what my cards are.

### Tasks
- [x] Implement socket "endpoint" for starting game
- [x] Implement logic to retrieve an unique card
- [x] Update the game for all clients when the game is started
- [x] Store each players card in the client.
- [x] Render the cards received from backend in the client.
- [x] Make sure correct user's card are displayed.

**Comment by albinr99salt** [comment]
Solved with https://github.com/albinr99salt/no-name/pull/24
