### ISSUE TITLE
use github server side hooks for deploy

### ISSUE THREAD

**Issue by Albin-Rohde** [albinr99salt/no-name#195]
Currently the deploy setup is not very good or stable.

Currently we are relying on a webhook server accepting requests from github and deploying the server. There are multiple issues with this. For starter the code that does the actual deploy is not checked in to this repo. Secondly it relies on a a specific deploy server being up and running. Furthermore it requires additional open ports on both the servers firewall, and the router.

Add unnecessary complexity to this and it is clear that another solution is needed.

### Solution:
Instead of relying on pushes to master execute some webhook we could set up the pi server as a remote on git.
This would mean that to deploy to master, one would push a specific branch to the server remote. We would then need some git hooks to execute the deploy on the "post_commit" event.

We should make sure that the deploy is as fast and smooth as possible.

### Tasks:
- [ ] Set up pi4 server as git remote
- [ ] Create script to setup server, change the hooks path (and check out the repo?)
- [ ] Create git hooks for deployment
- [ ] Make sure deployment are smooth and fast.
