### ISSUE TITLE
Join game functionality

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#2]
## Intro
When a game is crated by a user, it should be possible for other users to join the game. This should be handled by a websocket connection, as the game will be dependent on realtime data.

The first milestone should be to open a socket connection when a game is created, and allow other users to join that session. The connection should make sure to update all clients connected to game; that a new player has joined the game.

### Story
As a user i want people to be able to join my game, in addition i want to see when a new player has joined. I do not want my browser to poll the backend for new data, as that could "feel" slow and laggy.

I want my game to be secure, and i don't want people who i did not invite; being able to see any data about my game.

### Value
Users can join other users game, which will make it possible to start a game together.
Using websockets for this will make it very snappy and responsive.
We will establish a specific "socket-session" for a specific game. All players linked to a game will sort of subscribe to updates to the game.

### Criteria
- User can create a game
- A created game should open a socket connection.

- User should be able to join a game
- Joining a game should result in joining the "game connection".

- Websocket should not broadcast data to users outside of gamecontext see #1 

### Tasks
- #### Create game
- [x] Create game via static routes
- [x] Use key from game to establish socket connection on game room
- [x] Update game data on events

- #### Join game
- [x] Input game key
- [x] use game key from input to establish socket connection on game room
- [x] Update game data on events
- [x] User can not join a full game

**Comment by albinr99salt** [comment]
Progress can now be tracked at https://github.com/albinr99salt/no-name/pull/5

**Comment by albinr99salt** [comment]
Solved with https://github.com/albinr99salt/no-name/pull/5
Closing.
