### ISSUE TITLE
Clean up frontend clients

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#25]
With the new normalized Responses merged with https://github.com/albinr99salt/no-name/pull/24

We should look into how the clients store their internal data, is there any chance we could make that cleaner?

### Tasks
- [x] Implement new RestClient
- [x] Remove GameClient
- [x] Remove UserClient
- [x] Move away from using class instance as state
- [x] Fix issue with joining game

**Comment by albinr99salt** [comment]
GameClient could be renamed to SetupGameClient
And could be responsible for creating a game

We could then have a IngameClient responsible for sockets.

On the IngameClient the data from SetupGameClient could live in a gameOptions Object.

All data in the IngameClient should reflect the responseTypes.ts
