### ISSUE TITLE
Play card epic

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#26]
### Intro
Players should be able to play their cards. They should only be able to play it once, and only if they are not cardwizz.

### User Story
As a user i want to be able to play my card when a round begin. I want to be able to see that i have played my card. I only want to be able to play one card per round.

I do not want other people to be able to see my card until the cardwizz flips it.

#### Backend
- [x] Add A cardwizz (Cardwizz epic)
- [x] Add state to user, if they have played that round or not
- [x] Make sure user can only play a card once
- [x] Should keep track of when all players has played
#### Frontend
- [x] Make sure user can only play a card once
- [ ] How played cards are displayed should be randomized.

**Comment by albinr99salt** [comment]
**_"Should keep track of when all players has played"_**
I guess this info can be withdrawn from 
```javascript
const userThatHasPlayed = game.users.filter(u => u.has_played)
```

Marking as checked for now.

**Comment by albinr99salt** [comment]
_**How played cards are displayed should be randomized.**_
The first implementation of this caused some issues, this will have to be researched a bit, and will thus be added to a separate ticket.

**Comment by albinr99salt** [comment]
> **_"Should keep track of when all players has played"_**
> I guess this info can be withdrawn from
> 
> ```js
> const userThatHasPlayed = game.users.filter(u => u.has_played)
> ```
> 
> Marking as checked for now.

Yes, and thus the bool value of "everyone has played" would be something like:
```typescript
const allHasPlayed: bool = (game.users.length - 1) === game.users.filter(u => u.has_played).length
```
The question is if this should be done on backend, and added to the `GameResponse` or if it should be calculated on frontend.
