### ISSUE TITLE
Cardwizz Epic

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#27]
### Intro
In cards against humanity a Cardwizz is a designated player each round. That do not play any cards. Thei soul task is to vote which card was the most fun. Our game ofc needs a Cardwizz.

### User story
As a user i want to have a cardwizz in my game. I want to be able to see who that player is for that round. I also want it to be easy to see if i am the cardwizz for a specific round.

I want everyone in my game to be cardwizz an equal amount of times (roughly).

### Cardwizz story
As the Cardwizz i want to be able to easily see that i am the cardwizz. When i am the cardwizz i want to know when all players has played their card, so that i can start looking at them.
As the cardwizz, i want to be able to flip the players card; showing me the content.

### Tasks
- [x] Store a list of what users should be cardwizz for what round

#### This could be achieved by
- [x] Create a table called round_card_wizz
id, user_id_fk, game_key_fk, round_number
- [x] Populate round_card_wizz with data when game starts

#### Implementation - Backend
- [x] Use the table round_card_wizz to figure out if current player should be cardWizz
- [x] Should append it to the UserResponse

#### Implementation - Frontend
- [x] Frontend should set it as a bool in the client
- [x] Display it to the user who is cardwizz
- [x] Gray out the cards for the cardwizz (make them unable to play)
- [ ] Make it possible to vote for cards (Vote epic)

**Comment by albinr99salt** [comment]
- Make it possible to vote for cards (Vote epic)
Will not be included in this epic, Instead it will be continued worked on in a vote epic.

**Comment by albinr99salt** [comment]
Vote epic added, The rest of this Epic is completed.
