### ISSUE TITLE
Move Frontend into same repo

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#3]
This is something that just has to be done.

Frontend should be set up with propper docker env, one `docker-compose up` should start the entire platform

### Why?
- This will make the project centralised in one repo, easier to track in github project.
- Easier to deploy the project on any machine at any time

### Tasks
- [x] Move all existing code in frontend repo to `root/frontend`
- [x] Setup and configure docker for frontend repo
- [x] Move all existing code in backend repo to `root/server/`
- [x] Merge repo's
- [x] Add the new docker image as a new container in a docker-compose script on root
- [x] Profit

**Comment by albinr99salt** [comment]
The prep work for this will be started, more info will be added as research progress.
