### ISSUE TITLE
Game host

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#31]
We need a game host, and a way to identify who is the game host

## Story
What the game host can do:
- Game host is the only one that can start a game
- Game host is the only one that can delete a game
- Game host can not leave game

Other host specific things might be added later on in other tickets

## Tasks
- [x] Add `game_host_user_id` on `GameModel`
- [x] Make it easy to check if a user is host
- [x] Assign the creator of a game as the "game host"
- [x] only make it possible for the host to delete a game
- [x] only make it possible for the host to start a game

**Comment by albinr99salt** [comment]
Should this maybe be a nice to have?
