### ISSUE TITLE
Add posibility to leave game

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#34]
### Intro
It should be possible to leave a game.

### User story
As a user i want to be able to quit a game that i am currently playing in. I want to be able to do this at any given time.
It should be easy for me to understand how i quit, and the consequences of it. 

### Tasks
- [x] Add socket event for leaving a game
- [x] Add Button i frontend to leave game (top right corner)
- [x] Make sure game is updated for all other players in game
- [x] Game host can not leave game, Only terminate it #31

**Comment by albinr99salt** [comment]
One big issue that has to be resolved in the future.

When a player leave, the game_round table for that game will be wrong, since it calculated the cardwizz etc around the leaving user being in the game.

This will have to be fixed in a separate ticket later on.
