### ISSUE TITLE
Vote Epic

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#42]
### Intro
This intend to make it possible to vote for cards as the card wizz. 

### User Story
As a user i want the card wizz to be able to vote for the best card for each round. I want to clearly understand what card won, and what player had that card. I want to be able to see who's score has increased.

### Card wizz Story
As the card wizz i want to be able to flip the cards that other players has played, When all cards has been flipped i want to be able to vote for the card i thought was most fun. I want it to be clear when i am flipping and when i am voting.

I do not want to be able to vote before i have flipped all the cards.

#### Frontend
- [x] Fix so that cards are played upside down
- [x] Add functionality for card wizz to flip card
- [x] Make sure only Card Wizz can flip card
- [x] Make sure all players get to see the card when its flipped

#### Backend
- [x] Add flipCardEvent
- [x] Implement User.isCardWizz hybrid prop
- [x] Only card wizz can flipCard

#### Frontend
- [x] Display player score ingame
- [x] Add vote action (can only vote when all cards are flipped)
- [x] UI display in a clear way that the cardwizz can vote
- [x] Display the winner card and what user played the card

#### Backend
- [x] Store score on User
- [x] Add vote event (can only vote when all cards are flipped)
- [x] Add "winner" state to voted card
