### ISSUE TITLE
CurrentUser on Game model

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#59]
To solve the current issue with the two user instances the "root user" and the "currentUser", we should move away from using the user instance as our access point to a game and its users. And thereby the currentUser.

Instead what we pass around in the events and all the services should be a `Game` instance. The issue with this approach is that we lose the context of a currentUser,  Since our `Game` instance only holds a list of `Users` and does not know anything about who is implementing the game and what `User` in the list should be considered the "currentUser".

To solve this issue we can make the `Game` model a bit smarter and implement a geter and a setter on it.

What this means is that when instancing a `Game` instance, we could tell the game what user in the `Game.users` list should be considered the "currentUser".  Consequently it could implement a geter, so that doing `Game.currentUser` will act upon the specific `User` in the `Game.users` list. 

example

Class
```typescript
class Game {
  column: type
  ...
  private currentUserId: number
  
  set currentUser (user: User): void // sets value of private currentUserId from the user object in argument
  
  get currentUser (): User // gets the currentUser based on id assigned.
}
```

Implementation
```typescript
const game = new Game() // or Game.findeOne()
game.currentUser = session.user // session.user being a User instance on the session

// ... later in the event
game.currentUser.cards = cards
game.save()
```

After this has been done we can remove all uses of `User` as the root model for events and services, instead use the new and improved `Game`.

### Tasks
- [x] Add Setter and Geter on `Game`
- [x] Add function to get a correctly instanced `Game` with a currentUser
- [x] Refactor events and servises to use `Game.currentUser` instead

_Originally posted by @albinr99salt in https://github.com/albinr99salt/no-name/issues/53#issuecomment-814455140_

**Comment by albinr99salt** [comment]
fixed in https://github.com/albinr99salt/no-name/pull/61
